# Travis CI configuration file
# http://about.travis-ci.org/docs/

language: python

sudo: false

cache:
  pip: true

install:
  - pip install PyMeta3 coverage codecov flake8

script:
  - coverage run tests.py
  - flake8

after_success:
  - codecov
  
deploy:
  edge: true  # use latest v2 deploy
  provider: pypi
  #  skip_cleanup: true
  on:
    tags: true
